all:
  profiles:
    property: default value
---
spring:
  profiles: profileA
  
profile:
  a:
    property:
      only: profile A
---
spring:
  profiles: profileB
  
profile:
  b:
    property:
      only: profile B
  

